title: Heart Script Studio
description: "Creative AI blog and studio"
baseurl: "/heartscript-blog"
url: "https://abiy227.github.io"

# Navigation (optional depending on your theme)
nav:
  - title: "Home"
    url: "/"
  - title: "Services"
    url: "/services/"
  - title: "Request"
    url: "/request/"
  - title: "Products"
    url: "/products/"
