title: Heart Script Studio
description: Welcome to Heart Script Studio — AI-powered creative services and products.
baseurl: "/heartscript-blog" # matches your repo name
url: "https://abiy227.github.io"

theme: minima
plugins:
  - jekyll-feed
